### ISSUE TITLE
Cloning into 'predix-machine-template-processor'...fatal: Remote branch 2.2.4 not found in upstream origin

### ISSUE THREAD

**Issue by robsmithies** [PredixDev/predix-machine-template-processor#1]
With  reference to the following tutorial to add Predix Machine to an edge device (in this case a Raspberry Pi)...

https://www.predix.io/resources/tutorials/tutorial-details.html?tutorial_id=1742&tag=1750&journey=Setup%20Raspberry%20Pi%20for%20Predix&resources=1785,1741,1742,1743

...when the following script is run in DevBox...

bash <( curl https://raw.githubusercontent.com/PredixDev/predix-machine-template-adapter-pi/master/scripts/quickstart-machine-pi.sh ) --skip-setup

...the following JSON file is referenced...

https://raw.githubusercontent.com/PredixDev/predix-machine-template-adapter-pi/master/version.json

...this references https://github.com/PredixDev/predix-machine-template-processor#2.2.4

However, there is no branch 2.2.4 in the above git repo. Instead the master is at 2.2.5 as of the latest submission on 22/02/2018.

This is causing the script in the above curl command to crash with the following output in a DevBox terminal window...

git clone https://github.com/PredixDev/predix-machine-template-processor -b 2.2.4
Cloning into 'predix-machine-template-processor'...
fatal: Remote branch 2.2.4 not found in upstream origin
Unexpected end of command stream

Is the fix to update version.json to point to 2.2.5, or create a 2.2.4 branch in the git repo, or something else?

**Comment by turnerth** [comment]
Good sleuthing.  You are spot on.  I've alerted the developer so they should reply soon with a fix.  

The other problem I see is that the version of Predix Machine is an old one.  We've had trouble recently with 17.1.2 versions of Predix Machine and the certificate issue, which means it won't launch after January 31st, 2018 (need to use 17.1.3).  Maybe the 16.x version is so old that it avoids that problem.  

I'll ask the developer about that too.

**Comment by susheelvc** [comment]
This issue is fixed with the current release. Please retry and let me know.
